#!/usr/bin/env python3
"""Generate notices for the frontend production dependency closure.

The shipped UI is a minified bundle, so its dependency license files do not
otherwise reach the Python wheel.  package-lock.json is the deterministic
inventory; node_modules supplies the exact upstream license text after
``npm ci``.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCK_PATH = ROOT / "ui" / "package-lock.json"
MODULES_PATH = ROOT / "ui" / "node_modules"
OUTPUT_PATH = ROOT / "THIRD_PARTY_NOTICES"

# A new license requires an explicit review instead of silently entering the
# release artifact.  These are all permissive and compatible with Apache-2.0.
# OFL-1.1 (reviewed 2026-07-17, F1): SIL Open Font License covering the
# bundled @fontsource woff2 files — redistribution in a larger work is
# permitted; attribution + license text ship in this notices file.
REVIEWED_LICENSES = {"Apache-2.0", "BSD-3-Clause", "ISC", "MIT", "OFL-1.1"}
LICENSE_FILENAMES = (
    "LICENSE",
    "LICENSE.md",
    "LICENSE.txt",
    "LICENCE",
    "LICENCE.md",
    "COPYING",
)


@dataclass(frozen=True, order=True)
class PackageNotice:
    name: str
    version: str
    license_id: str
    lock_path: str
    license_text: str

    @property
    def label(self) -> str:
        return f"{self.name} {self.version} ({self.license_id})"


def _package_name(lock_path: str) -> str:
    return lock_path.rsplit("node_modules/", 1)[1]


def _license_text(package_dir: Path) -> str:
    for filename in LICENSE_FILENAMES:
        candidate = package_dir / filename
        if candidate.is_file():
            return candidate.read_text(encoding="utf-8").strip()
    names = ", ".join(LICENSE_FILENAMES)
    raise RuntimeError(f"{package_dir}: no upstream license file ({names})")


def collect_notices() -> list[PackageNotice]:
    lock = json.loads(LOCK_PATH.read_text(encoding="utf-8"))
    packages: list[PackageNotice] = []
    for lock_path, metadata in lock["packages"].items():
        if not lock_path or metadata.get("dev", False):
            continue
        license_id = metadata.get("license")
        if license_id not in REVIEWED_LICENSES:
            raise RuntimeError(
                f"{lock_path}: unreviewed or missing license {license_id!r}"
            )
        package_dir = ROOT / "ui" / lock_path
        packages.append(
            PackageNotice(
                name=_package_name(lock_path),
                version=metadata["version"],
                license_id=license_id,
                lock_path=lock_path,
                license_text=_license_text(package_dir),
            )
        )
    return sorted(packages)


def render_notices(packages: list[PackageNotice]) -> str:
    groups: dict[str, list[PackageNotice]] = defaultdict(list)
    texts: dict[str, str] = {}
    for package in packages:
        digest = hashlib.sha256(package.license_text.encode()).hexdigest()
        groups[digest].append(package)
        texts[digest] = package.license_text

    lines = [
        "napflow third-party software notices",
        "",
        "The napflow wheel contains a pre-built browser UI. This file records",
        "the production dependency closure from ui/package-lock.json, including",
        "type-only packages that npm records in that closure. Inclusion here is",
        "conservative and does not imply that every listed file survives bundling.",
        "",
        "Generated by tools/generate_frontend_notices.py; do not edit by hand.",
        "",
        "Dependency inventory",
        "--------------------",
    ]
    lines.extend(f"- {package.label}" for package in packages)
    lines.extend(["", "Upstream license texts", "----------------------"])

    for digest in sorted(groups, key=lambda item: groups[item][0].label):
        lines.extend(["", "Packages:"])
        lines.extend(f"- {package.label}" for package in groups[digest])
        lines.extend(["", texts[digest]])

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when THIRD_PARTY_NOTICES differs from generated output",
    )
    args = parser.parse_args()
    rendered = render_notices(collect_notices())
    if args.check:
        if (
            not OUTPUT_PATH.is_file()
            or OUTPUT_PATH.read_text(encoding="utf-8") != rendered
        ):
            raise SystemExit(
                "THIRD_PARTY_NOTICES is stale; run "
                "tools/generate_frontend_notices.py after npm ci"
            )
        return 0
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
